### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by WJ-Yuan** [NOTF-API/IsaacBoxClient#1]
将父组件命名为 `Main`，其中一个`subMenu` 命名为 `Collect`，`search` 没有命名可以自己命名下
通过 `vue-devtool` 可以看到每次输入值的改变都会触发父组件的 render 和 patch；
![without memo](https://github.com/NOTF-API/IsaacBoxClient/assets/59187817/7abc1a06-4543-4b66-a266-fc674fd8b8dc)

有 memo 时，因为只有 submenu 的值改变才会触发 Collect 的重新渲染，因此从图上我们可以看到再次输入时，不会有 Collect 了
![with memo](https://github.com/NOTF-API/IsaacBoxClient/assets/59187817/7a17f8ce-75b4-4b5c-b372-6337db499c1e)

造成性能问题的原因是比起 JS 直接计算，每次动态样式和类的 虚拟DOM 计算是很耗时的，如果不添加 Memo，可以将这些样式计算提前到 JS 里算出，然后 `item.class` 来绑定样式

**Comment by NOTF-API** [comment]
感谢，已解决 参考文档https://cn.vuejs.org/api/built-in-directives.html#v-memo
